# Generated by Django 6.0.1 on 2026-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('capacity_kg', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Route', 'On Route'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
            ],
        ),
    ]
