# Generated by Django 6.0.1 on 2026-01-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Accident', 'Accident'), ('Breakdown', 'Breakdown'), ('Delay', 'Delay'), ('Lost Cargo', 'Lost Cargo'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('related_entity_id', models.CharField(blank=True, help_text='ID of related shipment, route, etc.', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/photos/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='incidents/docs/')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='vehicles.vehicle')),
            ],
        ),
    ]
