# Generated by Django 6.0.1 on 2026-01-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('service_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='destinations.destination')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='service_types.servicetype')),
            ],
            options={
                'unique_together': {('service_type', 'destination')},
            },
        ),
    ]
