# Generated by Django 6.0 on 2025-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_driver_status_alter_vehicle_capacity_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='incidents/docs/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/photos/'),
        ),
    ]
