# Generated by Django 6.0.1 on 2026-01-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_distance_km', models.FloatField(blank=True, null=True)),
                ('actual_duration_hours', models.FloatField(blank=True, null=True)),
                ('fuel_consumed_liters', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='drivers.driver')),
            ],
        ),
    ]
