# Generated by Django 6.0 on 2025-12-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='actual_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='fuel_consumed_liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_fees', models.JSONField(blank=True, default=dict)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_weight_kg', models.FloatField(default=1000)),
                ('estimated_time_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('urgency', models.CharField(choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Express', 'Express'), ('Critical', 'Critical')], default='Standard', max_length=20)),
                ('vehicle_types', models.JSONField(blank=True, default=list)),
                ('conditions', models.TextField(blank=True)),
                ('conflicts_with', models.JSONField(blank=True, default=list)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='logistics.servicetype')),
            ],
        ),
    ]
