# Generated by Django 6.0 on 2025-12-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_route_actual_distance_km_route_actual_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='logistics.destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('service_type', 'destination')},
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='conflicts_with',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='estimated_time_range',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='extra_fees',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='maximum_weight_kg',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='minimum_charge',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='region',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='vehicle_types',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='zone',
        ),
    ]
