# Generated by Django 6.0.1 on 2026-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='additional_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='allowed_package_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='driver_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='pricing_model',
            field=models.CharField(default='Distance-based', max_length=50),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
