# Generated by Django 6.0.1 on 2026-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('delivery_zone', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('type', models.CharField(choices=[('Stock Warehouse', 'Stock Warehouse'), ('Main Hub', 'Main Hub'), ('Checkpoint', 'Checkpoint'), ('Regular', 'Regular')], max_length=50)),
                ('destination_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='Domestic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
